all:
	g++ main.cpp Core.cpp Pipeline.cpp Instruction_Packet.cpp RISCV.cpp GUI.cpp -w -I ../include -o ../bin/RISCV

clean:
	rm -f *.o *~ *.bak ../bin/RISCV
	rm -f *.o *~ *.bak ../gui/src/components/filedata.json
	rm -f *.o *~ *.bak ../bin/Data\ Memory.mc